BUCKET_NAME = "stylizertest"
ACCESS_KEY_ID = "AKIASH3LEUK23GNFK6NZ"
SECRET_ACCESS_KEY = "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"

SD_API_KEY = "lUHfz6htjXph9Is7ZkuoIp218ZFbs1eqQRgI7MI9SuZR7ULbGR8XUZAhgYBh"
MODEL_ID = "dreamlike"

OPENAI_API_KEY = "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"
